networks:
  kafka-internal:
    external: true

volumes:
  broker3-data:
  broker1-data:
  broker2-data:

services:
  broker3:
    image: confluentinc/cp-kafka:8.3.1
    container_name: broker3
    hostname: broker3
    restart: unless-stopped
    ports:
      - "9081:9092"
      - "9083:9094"
    environment:
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"

      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: "broker,controller"

      # Все listener-ы теперь SSL
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:9094"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://broker3:9092,EXTERNAL://localhost:9083"

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:SSL,CONTROLLER:SSL,EXTERNAL:SSL"

      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@broker1:9093,2@broker2:9093,3@broker3:9093"

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

      # SSL параметры
      KAFKA_SSL_CLIENT_AUTH: "required"
      KAFKA_SSL_KEYSTORE_FILENAME: broker3.keystore.jks
      KAFKA_SSL_KEYSTORE_CREDENTIALS: broker3_keystore_creds
      KAFKA_SSL_KEY_CREDENTIALS: broker3_sslkey_creds
      KAFKA_SSL_TRUSTSTORE_FILENAME: broker3.truststore.jks
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: broker3_truststore_creds

    volumes:
      - broker3-data:/var/lib/kafka/data
      - ./ssl/broker3:/etc/kafka/secrets:ro
    networks:
      - kafka-internal

  broker1:
    image: confluentinc/cp-kafka:8.3.1
    container_name: broker1
    hostname: broker1
    restart: unless-stopped
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"

      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"

      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:9094"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://broker1:9092,EXTERNAL://localhost:9094"

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:SSL,CONTROLLER:SSL,EXTERNAL:SSL"

      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@broker1:9093,2@broker2:9093,3@broker3:9093"

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

      # SSL параметры
      KAFKA_SSL_CLIENT_AUTH: "required"
      KAFKA_SSL_KEYSTORE_FILENAME: broker1.keystore.jks
      KAFKA_SSL_KEYSTORE_CREDENTIALS: broker1_keystore_creds
      KAFKA_SSL_KEY_CREDENTIALS: broker1_sslkey_creds
      KAFKA_SSL_TRUSTSTORE_FILENAME: broker1.truststore.jks
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: broker1_truststore_creds

    volumes:
      - broker1-data:/var/lib/kafka/data
      - ./ssl/broker1:/etc/kafka/secrets:ro
    networks:
      - kafka-internal

  broker2:
    image: confluentinc/cp-kafka:8.3.1
    container_name: broker2
    hostname: broker2
    restart: unless-stopped
    ports:
      - "9093:9092"
      - "9095:9094"
    environment:
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"

      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: "broker,controller"

      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:9094"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://broker2:9092,EXTERNAL://localhost:9095"

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:SSL,CONTROLLER:SSL,EXTERNAL:SSL"

      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@broker1:9093,2@broker2:9093,3@broker3:9093"

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

      # SSL параметры
      KAFKA_SSL_CLIENT_AUTH: "required"
      KAFKA_SSL_KEYSTORE_FILENAME: broker2.keystore.jks
      KAFKA_SSL_KEYSTORE_CREDENTIALS: broker2_keystore_creds
      KAFKA_SSL_KEY_CREDENTIALS: broker2_sslkey_creds
      KAFKA_SSL_TRUSTSTORE_FILENAME: broker2.truststore.jks
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: broker2_truststore_creds

    volumes:
      - broker2-data:/var/lib/kafka/data
      - ./ssl/broker2:/etc/kafka/secrets:ro
    networks:
      - kafka-internal

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    restart: unless-stopped
    depends_on:
      - broker1
      - broker2
      - broker3
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: "local-ssl"
      # Подключаемся по SSL внутри сети
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "broker1:9092,broker2:9092,broker3:9092"
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: "SSL"
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_LOCATION: /etc/kafka-ui/secrets/broker1.truststore.jks
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_PASSWORD: "changeit"
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_KEYSTORE_LOCATION: /etc/kafka-ui/secrets/broker1.keystore.jks
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_KEYSTORE_PASSWORD: "changeit"
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_KEY_PASSWORD: "changeit"
    volumes:
      - ./ssl/broker1:/etc/kafka-ui/secrets:ro
    networks:
      - kafka-internal

  init-topics:
    image: confluentinc/cp-kafka:8.3.1
    container_name: acl-init-topics
    restart: "no"
    depends_on:
      - broker1
      - broker2
      - broker3
    networks:
      - kafka-internal
    environment:
      KAFKA_BOOTSTRAP_SERVER: broker1:9092
      PARTITIONS: "8"
      REPLICATION_FACTOR: "3"
    volumes:
      - ./scripts/setup-acls.sh:/setup-acls.sh:ro
      - ./ssl/broker1:/etc/kafka/secrets:ro
    entrypoint: ["/bin/bash", "/setup-acls.sh"]